name: Test Reusable with Number

on:
  workflow_call:
    inputs:
      days:
        description: 'Number of days'
        required: false
        type: number
        default: 7

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test input
        run: echo "Days received:" ${{ inputs.days }}
